### ISSUE TITLE
Roadmap and Issues

### ISSUE THREAD

**Issue by dhiachou** [Safe-T/rdp-rb#1]
Use github's Issues system for the roadmap instead of the readme file

**Comment by bararchy** [comment]
We will make a better order in things in the coming days.
We will open issues and milestones for the 1.0 release

**Comment by ik5** [comment]
Hi @dhiachou , I have started to create a roadmap, and it's an on going process :)

Thank you

**Comment by dhiachou** [comment]
@ik5  I will try to help as much as I can

**Comment by ik5** [comment]
Thank you @dhiachou :)
