### ISSUE TITLE
X224 Header has duplicate attributes

### ISSUE THREAD

**Issue by dhiachou** [Safe-T/rdp-rb#10]
I believe `@variable_part == @variable + LF`. So why do we have two of these? it is possible to get rid of that LF since  rdp-rb/lib/rdp/headers/x224.rb:176 by adding `.chomp` after `byteslice`.

**Comment by ik5** [comment]
The specs claims that I must calculate the length of the variable part together with \r\n, and it's also part of the data, but represents it's boundary.

So I prefer to keep it, so not to lose any data, but if I require to use it without it, then I'll chomp it.
